<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'>
<meta name='applicable-device' content='pc'><meta name='keywords' content='电脑,电脑讲解,电脑技术,编程,电脑故障维修Java Exceptions' />
<script src='../../highlight/highlight.pack.js'></script>
<link rel='stylesheet' type='text/css' href='../../highlight/styles/monokai.css'/>

<link rel='stylesheet' href='../../fenxiang/dist/css/share.min.css'>
<script src='../../fenxiang/src/js/social-share.js'></script>
<script src='../../fenxiang/src/js/qrcode.js'></script>

</head><body><script>hljs.initHighlightingOnLoad();</script><script>
var system ={};  
var p = navigator.platform;       
system.win = p.indexOf('Win') == 0;  
system.mac = p.indexOf('Mac') == 0;  
system.x11 = (p == 'X11') || (p.indexOf('Linux') == 0);     
if(system.win||system.mac||system.xll){
document.write("<link href='../css/3.css' rel='stylesheet' type='text/css'>");}else{ document.write("<link href='../css/3wap.css' rel='stylesheet' type='text/css'>");}</script><script src='../../js/3.js'></script><div class='div2'><div class='heading_nav'><ul><div><li><a href='../../index.html'>首页</a></li>
</div><div onclick='hidden1()' >分享</div>
</ul></div></div>
<div id='heading_nav2'> 
<li class='row' >
<div class='social-share' data-mode='prepend'><a href='javascript:' class='social-share-icon icon-heart'></a></div></li></div><script charset='utf-8' src='../../3/js/hengfu.js'></script><script charset='utf-8' src='../../3/js/hengfu2.js'></script><hr><div class='div1'><div class='biaoti'><center>Java Exceptions</center></div><div class='banquan'>原文出处:本文由博客园博主liuxuhelloworld提供。<br/>
原文连接:https://www.cnblogs.com/liuxuhelloworld/p/12005168.html</div><br>
    <h1 id="常见错误分类">1. 常见错误分类</h1>
<p>一般的，errors可以分为以下几类：</p>
<ul>
<li>user input errors</li>
<li>device errors or physical limitations</li>
<li>code errors</li>
</ul>
<h1 id="常用错误处理方式">2. 常用错误处理方式</h1>
<h2 id="error-code">2.1 error code</h2>
<p>一种常用的错误处理方法是返回error code，由calling method根据error code做不同处理。</p>
<p>但是有些情形下error code并不方便使用，比如如何取分错误码和与错误码相同的有效值。</p>
<h2 id="exception-handling">2.2 exception handling</h2>
<p>The mission of exception handling is to transfer control from where the error occured to an error handler that can deal with the situation.</p>
<p>当出现错误时，程序应当恢复到某个安全状态并重新来过，或者保存当前工作安全退出，但是这并不容易，关键就是程序控制权如何从触发错误的地方跳转到处理错误的地方。</p>
<p>Java allows every method an alternative exit path if it is unable to complete its task in the normal way：</p>
<ul>
<li>首先，throws an object that encapsulates the error information</li>
<li>然后，the exception-handling mechanism begins its search for an exception handler that can deal with this particular error condition</li>
<li>注意，这条alternative exit path与正常的程序逻辑无关，the method exits immediately, and it does not return its normal value, and the execution does not resume at the code that called the method</li>
</ul>
<h1 id="java-exception-hierarchy">3. Java exception hierarchy</h1>
<h2 id="throwable">3.1 Throwable</h2>
<p>Throwable是整个Java exception hierarchy的基类，其下分为：</p>
<ul>
<li>Error</li>
<li>Exception</li>
</ul>
<h2 id="error">3.2 Error</h2>
<p>the error hierarchy describes internal errors and resource exhaustion situations inside the Java runtime system.</p>
<p>You should not throw an object of this type. There is little you can do if sucn an internal error occurs, beyond notifying the user and trying to terminate the program gracefully.</p>
<h2 id="exception">3.3 Exception</h2>
<p>Exception可以分为两类：</p>
<ul>
<li>RuntimeException</li>
<li>其他</li>
</ul>
<p>RuntimeException意味着编码错误，比如<br />
a bad cast, an out-of-bounds array access, a null pointer access等。</p>
<p>其他Exception一般是出现了某种意外，some bad things happened, 比如，打开一个不存在的文件。</p>
<p>为什么打开不存在的文件不是RuntimeException？因为这不是你的代码能控制的，你先校验文件是否存在也没用，可能你校验时是存在的，但你打开时就不存在了。</p>
<h1 id="checked-exception-vs-unchecked-exception">4. Checked exception vs unchecked exception</h1>
<p>Error和RuntimeException这两支，我们称为unchecked exception.</p>
<p>除Error和RuntimeException这两支外的其他Exception，我们称为checked exception.</p>
<p>The compiler checks that you provide exception handlers for all checked exceptions:</p>
<ul>
<li>对于Error，你无能为力，所以是unchecked exception</li>
<li>对于RuntimeException，编码错误是你的责任，你应当避免它们出现，所以也是unchecked exception</li>
<li>对于其他exceptions，你必须做好处理它们的准备，所以是checked exception</li>
</ul>
<h1 id="checked-exception-declaration">5. Checked exception declaration</h1>
<p>对于你的方法可能抛出的checked exceptions，你必须在method declaration中通过throws声明出来。</p>
<p>如果可能抛出多个checked exceptions，那么需要都列出来，使用逗号分隔。</p>
<pre><code><code>public Image loadImage(String name) throws FileNotFoundException, EOFException {...}</code></code></pre>
<p>注意，unchecked exception不应当出现在你的throws声明中：</p>
<ul>
<li>对于Error，你无能为力</li>
<li>对于RuntimeException，你应当避免它们出现，而不是声明可能抛出它们。</li>
</ul>
<h1 id="throw-an-exception">6. Throw an exception</h1>
<p>如何抛出exception呢？很简单：</p>
<ul>
<li>find an appropriate exception class</li>
<li>make an object of that class</li>
<li>throw it</li>
</ul>
<p>没有合适的standard exception class可用？没有关系，你可以自定义一个</p>
<pre><code><code>class FileFormatException extends IOException {
    public FileFormatException() {}
    public FileFormatException(String gripe) {
        super(gripe);
    }
}</code></code></pre>
<p>一般的，我们为自定义的exception class提供两个constructors：a default constructor and a constructor with a detailed message.</p>
<h1 id="catch-exceptions">7. Catch exceptions</h1>
<pre><code><code>try {
    xxx
} catch (ExceptionType1 | ExceptionType 2 e) {
    xxx
} catch (ExceptionType3 e) {
    xxx
}</code></code></pre>
<p>对于checked exceptions，如果你知道如何处理它们，那么你可以catch它们，这样就不用抛出它们了。</p>
<p>As a general rule, you should catch those exceptions that you know how to handle and propagate those that you do not know how to handle.</p>
<h1 id="rethrow-exceptions">8. Rethrow exceptions</h1>
<pre><code><code>try {
    xxx
} catch (SQLException e) {
    throw new ServletException(&quot;xxx error&quot;).initCause(e);
}</code></code></pre>
<p>这是rethrow exception的常用方式。通过这种方式，我们可以包装出一个更抽象的exception，或者把一个checked exception转换成一个RuntimeException.</p>
<h1 id="finally">9. finally</h1>
<pre><code><code>try {
    try {
        xxx
    } finally {
        xxx
    }
} catch (Exception e) {
    xxx
}</code></code></pre>
<p>the inner try block has a single responsibility: to make sure that the resources are released</p>
<p>the outer try block has a single responsibility: to ensure that errors are reported.</p>
<p>注意，the body of the finally clause is intended for cleaning up resources. Don't put statements that change the control flow (return, throw, break, continue) inside a finally clause.</p>
<h1 id="try-with-resources">10. try-with-Resources</h1>
<pre><code><code>try (Resource res = xxx) {
    xxx
}</code></code></pre>
<p>从Java 7开始，try-finally结构可以简化为try-with-Resources.</p>
<p>要求Resource必须是AutoCloseable的实现类，when the try block exits, then res.close() is called automatically.</p>
<p>A difficulty arises when the try block throws an exception and the close method also throws an exception. The original exception is rethrown, and any exceptions thrown by close methods are considered &quot;suppressed&quot;. They are automatically caught and added to the original exception with the addSuppressed method.</p>


</div><hr><script charset='utf-8' src='../../js/sming.js'></script></body></html>